fix: app integration takes to wrong org
thrivedesk/wp-thrivedesk pull request #106
Opened 2024-10-31 13:52 UTC by Alamin-Ahammed

![image](https://github.com/user-attachments/assets/406088cd-3146-4766-8f9d-6c6c8efa2488)

See the above image, clicking this connect button takes to the wrong org. It was for not updateing the wp system info and some necessary data correctly. Here it is fixed. 

Dependecy: with frontend (app-frontend) td
(sonner link will be added )

2024-11-03 06:03 UTC, Rijoanul-Shanto commented on resources/js/admin.js
> +								console.log('data system info updted')
remove console log

2024-11-03 10:24 UTC, Alamin-Ahammed commented on resources/js/admin.js
> +								console.log('data system info updted')
but it is intensional. It will help us to debug.

2024-11-04 11:32 UTC, shamsbd71 commented
[wp-thrivedesk_v2.0.8.zip](https://github.com/user-attachments/files/17617487/wp-thrivedesk_v2.0.8.zip)

2024-11-10 14:51 UTC, Rijoanul-Shanto requested changes
add changelogs

2024-11-11 03:49 UTC, Alamin-Ahammed commented
> add changelogs

already added but need to modify: 
![image](https://github.com/user-attachments/assets/61eb16e9-d521-4b48-86f7-2350f17952b3)

2024-11-11 08:19 UTC, merged