feat - helpdesk_setting & conversations
thrivedesk/wp-thrivedesk pull request #23
Opened 2022-08-24 08:40 UTC by atiq-ur

1. Add Helpdesk settings on Thrivedesk setting option
2. Add Conversation Shortcode
3. Add Conversation list page with pagination
4. Add Conversation detail page
5. Add reply option on detail page (using TinyMCE editor)
6. Add new ticket modal with dynamic search option

[Video link](https://www.loom.com/share/52dbe5d7ae044dc68381ba1336c64cc9) -

2022-08-24 11:18 UTC, alaminfirdows requested changes

2022-08-24 11:18 UTC, alaminfirdows commented on includes/views/shortcode/modal.php
> +					<svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a
move it to file

2022-08-24 11:18 UTC, alaminfirdows commented on src/Conversations/Conversation.php
> +			include THRIVEDESK_DIR. '/includes/views/shortcode/conversation-details.php';
use `thrivedesk_view`

2022-08-24 11:18 UTC, alaminfirdows commented on src/Conversations/Conversation.php
> +		$dom = new DOMDocument('1.0', 'UTF-8');
why we need this?

2022-08-24 11:18 UTC, alaminfirdows commented on src/Conversations/Conversation.php
> +	public function getSelectedHelpdeskOptions() {
it should be moved to parent

2022-08-24 11:18 UTC, alaminfirdows commented on src/Conversations/Conversation.php
> +	public static function diffForHumans($datetime, $full = false): string {
move it to helper

2022-08-24 11:18 UTC, alaminfirdows commented on src/FormProviders/FormProviderHelper.php
> +class FormProviderHelper {
Do we need this?

2022-08-24 11:18 UTC, alaminfirdows commented on src/RestRoute.php
> +        add_action('rest_api_init', array($this, 'form_routes'));
what is `form_routes`?

2022-08-24 11:18 UTC, alaminfirdows commented on thrivedesk.php
> +        $this->define('THRIVEDESK_API_URL', 'http://api.thrivedesk.test');
change to the prod url

2022-08-24 11:19 UTC, alaminfirdows commented
You should clean the codebase, organize css class names and re-indent.

2022-08-24 13:43 UTC, atiq-ur commented on src/FormProviders/FormProviderHelper.php
> +class FormProviderHelper {
no

2022-08-24 13:43 UTC, atiq-ur commented on src/RestRoute.php
> +        add_action('rest_api_init', array($this, 'form_routes'));
should be conversation routes

2022-08-25 06:15 UTC, atiq-ur commented on includes/views/shortcode/conversations.php
> +include THRIVEDESK_DIR. '/includes/views/shortcode/modal.php';
solved by adding ```thrivedesk_view```

2022-08-25 06:17 UTC, atiq-ur commented on src/Conversations/Conversation.php
> +		$dom = new DOMDocument('1.0', 'UTF-8');
Need to parse html body content, means if html body does not contain end tag then, it brakes the style of the conversation. That is why we catch the errors and shows the actual element.

2022-08-25 06:17 UTC, atiq-ur commented on src/Conversations/Conversation.php
> +	public static function diffForHumans($datetime, $full = false): string {
moved

2022-08-25 06:18 UTC, atiq-ur commented on src/FormProviders/FormProviderHelper.php
> +class FormProviderHelper {
deleted

2022-08-25 06:18 UTC, atiq-ur commented on src/RestRoute.php
> +        add_action('rest_api_init', array($this, 'form_routes'));
moved to td routes

2022-08-25 06:58 UTC, atiq-ur commented on includes/views/shortcode/modal.php
> +					<svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a
moved

2022-08-25 11:08 UTC, atiq-ur commented on src/Conversations/Conversation.php
> +	public function getSelectedHelpdeskOptions() {
Resolved. Moved to helper function

2022-08-25 11:09 UTC, atiq-ur commented on thrivedesk.php
> +        $this->define('THRIVEDESK_API_URL', 'http://api.thrivedesk.test');
prod url should be changed on deploy time

2023-03-17 04:30 UTC, merged