feat: is guest customer identifier added
thrivedesk/wp-thrivedesk pull request #25
Opened 2022-11-23 08:13 UTC by pronob1010

Now we are able to identify a contact that is a normal customer or a guest customer. 
Related pull request : https://github.com/thrivedesk/app-frontend/pull/468

2022-11-23 08:16 UTC, Rijoanul-Shanto commented on src/Plugins/WooCommerce.php
> +
need proper formatting

2022-11-23 08:19 UTC, Rijoanul-Shanto commented on src/Plugins/WooCommerce.php
> +    public $orders = [];
add doc string to describe the variable

2022-11-23 09:19 UTC, Rijoanul-Shanto commented on src/Plugins/WooCommerce.php
>          $customer_orders = $query->get_orders();
are you sure there still isn't a double query?

2022-11-23 12:44 UTC, pronob1010 commented on src/Plugins/WooCommerce.php
> +
Done.

2022-11-23 12:47 UTC, pronob1010 commented on src/Plugins/WooCommerce.php
> +    public $orders = [];
fixed.

2022-11-23 13:03 UTC, pronob1010 commented on src/Plugins/WooCommerce.php
>          $customer_orders = $query->get_orders();
I had added a checker on the **is_guest** method and I thought that could handle that extra query but I was wrong. Now, I tested and just added a checker here so that we can ignore double query.

2022-11-23 16:44 UTC, Rijoanul-Shanto commented on src/Plugins/WooCommerce.php
> +
still there is an extra line break here 👻

2022-11-23 17:00 UTC, Rijoanul-Shanto commented on src/Plugins/WooCommerce.php
> +        if (empty($this->orders)) {
you are doing great, but we need to do better than that. If you look closely, you can optimize this even further 👻 

Imagine what if there is no order for a guest user? still, we will reach this method twice :p And also query twice.

2022-11-23 17:00 UTC, Rijoanul-Shanto requested changes
LG but need more updates.

2022-11-24 06:06 UTC, pronob1010 commented on src/Plugins/WooCommerce.php
> +        if (empty($this->orders)) {
Ok!!! should I try with a flag? like I was knocked once or not? @Rijoanul-Shanto

2022-11-24 06:28 UTC, pronob1010 commented on src/Plugins/WooCommerce.php
> +        if (empty($this->orders)) {
BTW if you are a guest user then you must have at least 1 order.

2022-12-26 04:44 UTC, merged