Woocommerce2.0
thrivedesk/wp-thrivedesk pull request #54
Opened 2023-05-04 07:09 UTC by pronob1010

```diff
- WooCommerce integration. 
```

- [x] 1. Response method added and modified for data 
- [x] 2. Actions added (Update, delete, Quantity modification)

2023-07-26 06:15 UTC, atiq-ur requested changes
Important:  Before merging into the develop branch, you must write the changelog in readme,txt, version.

1. Update version from thrivedesk.php file
2. Update changelog and version from readme.txt file
3. Update version at the package.json

2023-07-26 06:15 UTC, atiq-ur commented on src/Api.php
> +	/**
Add type for params and do not need doc block, if not important.

2023-07-26 06:19 UTC, Rijoanul-Shanto commented on src/Api.php
> +	private $orderId = null;
WordPress and Laravel coding guidelines are different. User lowercase (with an underscore) when declaring variable, action/filter, and function names.

Read this: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/

2023-07-26 06:25 UTC, alaminfirdows requested changes
Be aware about formating!

2023-07-26 06:25 UTC, alaminfirdows commented on src/Plugins/WooCommerce.php
> +			'street'  => $order->get_shipping_address_1() . ' ' . $order->get_shipping_address_2() ?? '',
`get_shipping_address_2() ?? ''`

or `$order->get_shipping_address_1() . ' ' . ($order->get_shipping_address_2() ?? ''),`

2023-08-20 05:23 UTC, pronob1010 commented on src/Api.php
> +	private $orderId = null;
done

2023-08-20 05:54 UTC, pronob1010 commented on src/Plugins/WooCommerce.php
> +			'street'  => $order->get_shipping_address_1() . ' ' . $order->get_shipping_address_2() ?? '',
done

2023-08-21 05:53 UTC, pronob1010 commented on src/Api.php
> +	/**
done

2023-09-05 04:46 UTC, merged