feat: Payment & Shipping Methods added
thrivedesk/wp-thrivedesk pull request #86
Opened 2024-03-24 10:47 UTC by pronob1010

Payment & Shipping Methods added

![image](https://github.com/thrivedesk/wp-thrivedesk/assets/44565867/17e8415e-cee3-4674-b3fb-27df950b4b9f)

2024-03-25 11:54 UTC, Rijoanul-Shanto commented on src/Plugins/WooCommerce.php
> +			$product_id = $item->get_variation_id() ? $item->get_variation_id() : $item->get_product_id();
```php
$product_id = $item->get_variation_id() ?? $item->get_product_id();

```

2024-03-25 11:56 UTC, Rijoanul-Shanto commented on src/Services/PortalService.php
> +		'business-ltd',
We need to make this smarter. We shouldn't rely on adding plans directly here. Things should be verified via the ThriveDesk API.

2024-03-25 11:56 UTC, Rijoanul-Shanto requested changes
Almost LGTM 😃

2024-03-27 10:51 UTC, pronob1010 commented on src/Services/PortalService.php
> +		'business-ltd',
okay bhai

2024-03-28 19:29 UTC, merged